### ISSUE TITLE
Bug: bright_green not introduced until Click 7.0

### ISSUE THREAD

**Issue by neil-pozetroninc** [aio-libs/create-aio-app#32]
Currently, `setup.py` just has Click without a version as a requirement. However, the color `bright_green` wasn't introduced until Click 7.0 resulting in the following error with older versions.

```
Traceback (most recent call last):
  File "/home/neil/.local/bin/create-aio-app", line 11, in <module>
    sys.exit(main())
  File "/home/neil/.local/lib/python3.6/site-packages/create_aio_app/main.py", line 44, in main
    fg='bright_green',
  File "/usr/local/lib/python3.6/dist-packages/click/termui.py", line 374, in style
    raise TypeError('Unknown color %r' % fg)
TypeError: Unknown color 'bright_green'
```
The following commit introduced bright colors to `termui.py`: https://github.com/pallets/click/commit/4383f608ef80168cd3f344b814caec548834c57a

**Comment by Arfey** [comment]
PR welcome.
